### ISSUE TITLE
transferTransaction doesn't read amount form msg.nem.Transaction

### ISSUE THREAD

**Issue by gigonzalezs** [nemtech/nem2-prototyping-tool#11]
transferTransaction is only getting amount value from config.

we need a fix.

**Comment by jorisadri** [comment]
This will be fixed in the [next update](https://github.com/jorisadri/nem2-prototyping-tool/commit/118ce977296e8403115a0e88905600540a124a17)
The mosaic part of the transfer transaction will change so its possible to send multiple mosaics in one transaction.

**Comment by gigonzalezs** [comment]
@jorisadri do you have telegram alias?

**Comment by jorisadri** [comment]
jorisjaja
