### ISSUE TITLE
The cosignatureTransaction must forward the "msg" var

### ISSUE THREAD

**Issue by gigonzalezs** [nemtech/nem2-prototyping-tool#8]
The cosignatureTransaction must forward the "msg" var, including a node.send(msg);

If not, the flow is unable to continue with signing and announcement.

https://github.com/nemtech/nem2-prototyping-tool/blob/807d537d483134e3d7c4b1a4220ce93349ddb7b9/NEMNodes/transactions/cosignatureTransaction.js#L29

**Comment by jorisadri** [comment]
That is indeed a bug. 
you can perform the same function in the sign node and select 'cosign'.

**Comment by gigonzalezs** [comment]
OK. is cosignatureTransaction going to be deprecated?  The output message structure of cosignatureTransaction doesn't match with the input for signTransaction.

please see this flow: https://flows.nodered.org/flow/0fbb7b217e970760aab70f2221073cda

I patch the cosignatureTransaction in my local branch in order to fix this flow. but perhaps cosignatureTransaction is not needed at all.

**Comment by gigonzalezs** [comment]
In order to prevent confusion, I would glad to contribute and fix this class

**Comment by jorisadri** [comment]
Is it for you more logical to cosign a transaction in the sign node or having a different node for it? 
Having one way to cosign will indeed prevent confusion.

**Comment by gigonzalezs** [comment]
I Agree. In fact I removed the cosignatureTransaction from my [flow](https://flows.nodered.org/flow/0fbb7b217e970760aab70f2221073cda). thanks

We can discard my [pull request](https://github.com/nemtech/nem2-prototyping-tool/pull/9).

**Comment by jorisadri** [comment]
for know I tried to follow the nem2-sdk so if we would keep on following the sdk we should keep the coSignTransaction node and delete the cosign functionality

**Comment by gigonzalezs** [comment]
How can we help?

**Comment by jorisadri** [comment]
The code is changed. Now you need to add a cosignTransaction node to cosign a transaction. The signTransaction node detects when it need to sign or cosign a transaction.
